version: "2.2"
services:
    web:
        build: .
        restart: always
        ports:
            - "8080:8080"
        depends_on:
            - mongo
    mongo:
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - "27018:27017"
